import * as T from 'three';
import './style.css';
import {createHud, hudText} from './hud.js';
import {ROOMS,PATHS,KEY,CORE,CAMP,createGame,step,observe,ACTION_SCHEMA} from './game.js';
import {createPlayweftSoloClient} from './playweft-solo-client.js';
const $=id=>document.getElementById(id),canvas=$('world');
const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0x15282c);renderer.toneMapping=T.ACESFilmicToneMapping;
const hud=createHud();
const scene=new T.Scene();scene.fog=new T.FogExp2(0x15282c,.019);const camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,160);scene.add(new T.HemisphereLight(0xc3e8e3,0x253038,2.4));const sun=new T.DirectionalLight(0xffdfae,3.2);sun.position.set(-15,35,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-42,right:32,top:36,bottom:-56,far:110});sun.target.position.set(0,0,-20);scene.add(sun,sun.target);
const materials=new Map();function mat(color,emissive=0){const key=color+':'+emissive;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,roughness:.85,emissive,emissiveIntensity:emissive?.8:0}));return materials.get(key);}
function box(w,h,d,color,x,y,z,parent=scene){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),mat(color));mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function crystal(color,x,y,z,size=.65){const m=new T.Mesh(new T.OctahedronGeometry(size),mat(color,color));m.position.set(x,y,z);m.castShadow=true;scene.add(m);return m;}
// The same four rooms remain present at every curriculum stage.
for(const [i,r]of ROOMS.entries()){
 box(r.w,1.8,r.d,r.color,r.x,-.95,r.z);box(r.w+.25,.15,r.d+.25,0x83918a,r.x,-.06,r.z);
 for(let x=-6;x<=6;x+=3)for(let z=-6;z<=6;z+=3)box(2.9,.06,2.9,r.color,r.x+x,.025,r.z+z);
 for(const side of [-1,1])for(const front of [-1,1]){let x=r.x+side*6.9,z=r.z+front*6.9;box(1.5,.35,1.5,0x919487,x,.2,z);box(.85,2.6+(i%2)*.9,.85,0x6c7e78,x,1.6,z);box(1.25,.3,1.25,0x9ca496,x,3+(i%2)*.9,z);crystal(i===2?0xe5ba69:0x90d6ce,x,3.6+(i%2)*.9,z,.22);}
 // Broken low boundary stones leave clear doorways and sight lines.
 for(let j=-5;j<=5;j+=2.5){if(Math.abs(j)<3)continue;box(2,.55,.6,0x667b72,r.x+j,.25,r.z-7.5);box(.6,.55,2,0x667b72,r.x+7.5,.25,r.z+j);}
}
for(const p of PATHS){box(p.w,.7,p.d,0x6d807a,p.x,-.45,p.z);for(let k=-p.d/2+.4;k<p.d/2;k+=1)box(p.w,.06,.12,0xa0a99a,p.x,-.04,p.z+k);}
// Ruins float above a misty ravine; edge falls are recoverable but costly.
box(190,1,190,0x203b3b,0,-8,-20);
for(let i=0;i<55;i++){let x=Math.sin(i*29.3)*53,z=Math.cos(i*13.7)*52-20;if(Math.abs(x)<30&&z<10&&z>-52)continue;box(2+i%3,5+i%11,2+i%2,0x2c4646,x,-5,z);}
const gate=new T.Group();scene.add(gate);box(.9,5,1,0x94a69d,-3,2.5,-30,gate);box(.9,5,1,0x94a69d,3,2.5,-30,gate);box(6.8,.7,1,0x94a69d,0,5,-30,gate);const seal=box(5.2,4.8,.22,0x68b6c8,0,2.4,-30,gate);seal.material=new T.MeshStandardMaterial({color:0x62d8e9,emissive:0x287e99,transparent:true,opacity:.48});
box(2.7,.4,2.7,0xb8aa80,KEY.x,.2,KEY.z);const key=crystal(0xffc778,KEY.x,1.5,KEY.z,.55);
box(3,.6,3,0x718a90,CORE.x,.3,CORE.z);const core=crystal(0x95fff0,CORE.x,1.9,CORE.z,.8);const coreLight=new T.PointLight(0x72ffe0,9,11);coreLight.position.copy(core.position);scene.add(coreLight);
box(2.6,.25,2.6,0x817c62,CAMP.x,.1,CAMP.z);const fire=crystal(0xffb974,CAMP.x,.9,CAMP.z,.4);const tent=new T.Mesh(new T.ConeGeometry(2,2.8,4),mat(0xc2a879));tent.position.set(-4,1.4,4);tent.rotation.y=Math.PI/4;scene.add(tent);box(2,.5,.6,0x705943,4,.25,4);
const trap=box(5,.04,2.2,0xb09a69,0,.07,-24);trap.material=mat(0xaa765c,0x771c10).clone();for(let i=-2;i<=2;i++)box(.07,.07,2,0xdfbd7c,i,.1,-24);
function actor(color){const g=new T.Group();box(.7,.85,.45,color,0,1.1,0,g);box(.43,.44,.43,0xd6c9a2,0,1.79,0,g);box(.52,.18,.5,0x284545,0,2.06,0,g);const legs=[box(.23,.65,.26,0x293c3c,-.2,.4,0,g),box(.23,.65,.26,0x293c3c,.2,.4,0,g)];box(.19,.65,.22,color,-.49,1.03,0,g);const sword=box(.12,1.25,.13,0xe3e6d8,.52,1.05,.35,g);sword.rotation.x=.6;const cape=box(.65,.85,.08,0x294e56,0,1.1,-.28,g);cape.rotation.x=-.15;scene.add(g);return {g,legs,sword};}
const hero=actor(0x96cdc0),guard=actor(0xa68465);guard.g.scale.setScalar(1.35);const ring=new T.Mesh(new T.RingGeometry(.9,3.1,48),new T.MeshBasicMaterial({color:0xff7250,transparent:true,opacity:.45,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);
let state=createGame(2),started=false,paused=false,acc=0,last=performance.now(),agent=false,pending={},keys=new Set(),lookX=0,lookY=0,drag=false,pressX=0,pressY=0,attack=false,noticeTime=0,lastMessage='';
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();hud.resize(innerWidth,innerHeight);}addEventListener('resize',resize);resize();
function reset(level){state=createGame(level);started=true;paused=false;agent=false;keys.clear();pending={};acc=0;$('overlay').classList.add('hidden');$('pause').textContent='暂停 II';}
$('start').onclick=()=>reset(Number($('level').value));
function pause(){if(!started||state.status!=='playing')return;paused=!paused;keys.clear();$('pause').textContent=paused?'继续 ▶':'暂停 II';}
$('pause').onclick=pause;addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(started&&!paused&&state.status==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&state.status==='playing')pause();});
canvas.addEventListener('pointerdown',e=>{drag=true;pressX=e.clientX;pressY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(drag){lookX-=e.movementX*.004;lookY+=e.movementY*.003;}});canvas.addEventListener('pointerup',e=>{if(e.button===0&&Math.hypot(e.clientX-pressX,e.clientY-pressY)<6)attack=true;drag=false;});canvas.addEventListener('pointercancel',()=>{drag=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
function human(){const a={moveX:+keys.has('KeyD')-+keys.has('KeyA'),moveY:+keys.has('KeyW')-+keys.has('KeyS'),lookX:lookX+(+keys.has('ArrowLeft')-+keys.has('ArrowRight'))*.025,lookY:lookY+(+keys.has('ArrowDown')-+keys.has('ArrowUp'))*.015,jump:keys.has('Space'),attack:attack||keys.has('KeyJ'),dodge:keys.has('ShiftLeft')||keys.has('ShiftRight'),interact:keys.has('KeyE')};lookX=lookY=0;attack=false;return a;}
function end(){const win=state.status==='won',damage=state.damage;const panel=document.createElement('div');panel.className='panel';panel.innerHTML=`<small>远征记录 / 阶段 ${state.level}</small><h1>${win?'光已归来':'再试一次'}</h1><p>${win?'你把能量核心带回了营地。':state.message}</p><div class="route">用时 ${Math.floor(state.time/60)} 分 ${Math.floor(state.time%60)} 秒 · 剩余生命 ${state.p.hp}</div><ul><li>守卫伤害：${damage.guard} — 红圈出现时离开攻击范围或闪避</li><li>陷阱伤害：${damage.trap} — 暗下时穿过，或跳过符文</li><li>跌落伤害：${damage.fall} — 留意桥面与房间边界</li></ul><button class="primary" id="retry">再次远征 ↗</button><button id="export">导出本局记录</button>`;$('overlay').replaceChildren(panel);$('overlay').classList.remove('hidden');$('retry').onclick=()=>reset(state.level);$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(observe(state),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='relic-return-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
window.relicReturn={version:1,actionSchema:ACTION_SCHEMA,observe:()=>observe(state),reset:({level=2}={})=>{reset(level);agent=true;return observe(state);},act:(action={},frames=1)=>{agent=true;if(paused)return observe(state);for(let i=0;i<Math.max(1,Math.min(600,Math.floor(Number(frames)||1)));i++){const prev=state.status;step(state,action);if(prev==='playing'&&state.status!=='playing')end();}return observe(state);},resumeHuman:()=>{agent=false;state.prev={};keys.clear();}};
createPlayweftSoloClient();
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(started&&!paused&&!agent&&state.status==='playing'){acc+=dt;while(acc>=1/60){const prev=state.status;step(state,human());acc-=1/60;if(prev==='playing'&&state.status!=='playing')end();}}
 const p=state.p,e=state.enemy,t=now/1000;hero.g.position.set(p.x,p.y,p.z);hero.g.rotation.y=p.angle;hero.g.visible=!(p.inv>0&&Math.floor(t*16)%2);const moving=keys.has('KeyW')||keys.has('KeyS')||keys.has('KeyA')||keys.has('KeyD');hero.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(t*12+i*Math.PI)*.55:0);hero.sword.rotation.x=p.attack>0?-1.3+Math.sin(p.attack*12)*1.6:.6;guard.g.position.set(e.x,0,e.z);guard.g.visible=e.hp>0;guard.g.rotation.y=Math.atan2(p.x-e.x,p.z-e.z);guard.sword.rotation.x=e.phase==='windup'?-2:e.phase==='strike'?1.5:.5;ring.visible=e.hp>0&&['windup','strike'].includes(e.phase);ring.position.set(e.x,.12,e.z);ring.material.opacity=e.phase==='strike'?.75:.2+Math.sin(t*18)*.1;
 key.visible=!state.key&&!state.door;key.rotation.y=t;key.position.y=1.5+Math.sin(t*2)*.15;core.visible=!state.core;core.rotation.y=-t*.7;core.position.y=1.9+Math.sin(t*2)*.2;coreLight.visible=!state.core;seal.visible=!state.door;fire.rotation.y=t;fire.scale.setScalar(state.status==='won'?2:1);trap.visible=state.level>1;trap.material.emissiveIntensity=Math.sin(state.time*2)>.35?1.7:.12;
 const yaw=state.camera.yaw,pitch=state.camera.pitch,dist=9;const target=new T.Vector3(p.x+Math.sin(yaw)*Math.cos(pitch)*dist,p.y+2+Math.sin(pitch)*dist,p.z+Math.cos(yaw)*Math.cos(pitch)*dist);camera.position.lerp(target,1-Math.exp(-dt*9));camera.lookAt(p.x,p.y+1.2,p.z);renderer.render(scene,camera);
 $('location').textContent=ROOMS.find(r=>Math.abs(p.x-r.x)<r.w/2&&Math.abs(p.z-r.z)<r.d/2)?.name||'遗迹栈桥';
 if(lastMessage!==state.message){lastMessage=state.message;noticeTime=now+2600;}
 hud.update(hudText(state,paused,now<noticeTime?state.message:''));
 hud.render(renderer);
}camera.position.set(7,9,13);requestAnimationFrame(frame);
